name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore apis/poi/web/poi.csproj
    - name: Build Test
      run: dotnet build --configuration release apis/poi/tests/UnitTests/UnitTests.csproj 
    - name: Build Web
      run: dotnet build --configuration release apis/poi/web/poi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal apis/poi/tests/IntegrationTests/IntegrationTests.csproj
